# Generated by Django 3.0.2 on 2020-02-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200126_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Image'),
        ),
    ]
