# Generated by Django 2.2.7 on 2020-02-20 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200217_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ProductId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Rating',
            field=models.IntegerField(verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.UserProfileInfo', verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom de produit'),
        ),
    ]
