# Generated by Django 2.2.7 on 2020-02-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200220_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.TextField(default='', max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=250, verbose_name='Comment'),
        ),
    ]
