# Generated by Django 2.2.7 on 2020-02-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200220_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SecondImage',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Second Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='ThirdImage',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Third Image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Main Image'),
        ),
    ]
